### ISSUE TITLE
Unable to import private keys - (both from device and manually)

### ISSUE THREAD

**Issue by C00p3rb123** [dltxio/idem-mobile#340] opened 2022-08-04 02:12 UTC
Receiving this error with private keys that have worked before and with Test data

![image](https://user-images.githubusercontent.com/48899363/182748080-ec38c500-58f0-46b8-8e85-7f1c10fa15ce.png)

**Comment by pondpiu** [comment] 2022-08-04 02:58
key
https://github.com/dltxio/idem-mobile/blob/development/app/tests/alice.asc

**Comment by Jimjamin** [comment] 2022-08-11 07:03
Given current assessments, problem function seems to be: https://github.com/dltxio/idem-mobile/blob/6b9d96733f175a6d1a2208200577c08777f0f4b8/app/src/hooks/usePpg.ts#L64

This function calls the first part of the error message `There was a problem generating your public key...`. However it begins to get a bit weirder from there. It would seem that this function which is called in the OpenPGP library produces the next part of the error: https://github.com/jerson/react-native-fast-openpgp/blob/df7f27cc2b7978bdd2bf60d972063223a680e422/src/index.tsx#L719

However, there seems no reason for the function producing the error in IDEM to be calling the function producing the error in OpenPGP. Following the trail of errors from there to see where the 'invalid data' part comes in seems to be harder - not clearly documented is the OpenPGP library.

Also double checked the Alice keys themselves - they still have a couple of years till expiry and appear to be valid according to Kleopatra.

**Comment by Jimjamin** [comment] 2022-08-12 00:23
#243 

Seems the exact same function is having a problem here. The error messages are only different because the way the messages are structured were changed in #244 but I am unable to find what changes were made that closed this issue? Were there any changes made in a commit I could be pointed towards? 

Are there any log of test results relating to this specific function? I can't find any tests that relate to this function specifically? @pondpiu @JasminFarhi

**Comment by pondpiu** [comment] 2022-08-12 03:15
@Jimjamin the error in the screenshot originate from `OpenPGP.getPublicKeyMetadata(publicKey);` this line
https://github.com/dltxio/idem-mobile/blame/3fe0f23173ff25bbd54e3288b26e834afb2ab906/app/src/hooks/usePpg.ts#L66

which then get fixed by calling `OpenPGP.getPrivateKeyMetadata(privateKey);` instead
https://github.com/dltxio/idem-mobile/pull/355

I haven't found the root cause of it yet, but maybe public key that we get from converting private key lacks some metadata.

**Closed** 2022-08-30 03:57 UTC
Labels: bug
